src/Dinoco.WebDashboard/Models/Home/HomeIndexModel.cs
using System.Collections.Generic;

namespace Dinoco.WebDashboard.Models.Home
{
    public class HomeIndexModel
    {
        public List<StoreOverview> Stores { get; set; }

        public HomeIndexModel()
        {
            Stores = new List<StoreOverview>();
        }
    }
}

src/Dinoco.WebDashboard/Models/Home/StoreOverview.cs
using Dinoco.Shared.Models;
using Dinoco.Shared.Models.Telemetry;

namespace Dinoco.WebDashboard.Models.Home
{
    public class StoreOverview
    {
        public int StoreID { get; set; }

        public int CoffeeAge { get; set; }
        public double CoffeeTemperature { get; set; }


        public string CoffeeOverview
        {
            get
            {

                if (CoffeeAge <= 15)
                {
                    return "Fresh";
                }
                else if (CoffeeAge <= 40)
                {
                    return "Just Made";
                }
                else
                {
                    return "Old";
                }
            }
        }

        public int PeopleInStore { get; set; }

        public string FootTrafficOverview
        {
            get
            {

                if (PeopleInStore <= 10)
                {
                    return $"Slow - {PeopleInStore} souls";
                }
                else if (PeopleInStore <= 20)
                {
                    return $"Steady- {PeopleInStore} souls";
                }
                else
                {
                    return $"Busy- {PeopleInStore} souls";
                }
            }
        }

        public decimal E85Level { get; set; }
        public decimal AllinolLevel { get; set; }
        public decimal DieselLevel { get; set; }

        public string E85DisplayClass
        {
            get
            {
                if (E85Level <= 15)
                {
                    return "fuel-danger";
                }
                else if (E85Level <= 50)
                {
                    return "fuel-warning";
                }
                else
                {
                    return "fuel-good";
                }
            }
        }



        public string AllinolDisplayClass
        {
            get
            {
                if (AllinolLevel <= 15)
                {
                    return "fuel-danger";
                }
                else if (AllinolLevel <= 50)
                {
                    return "fuel-warning";
                }
                else
                {
                    return "fuel-good";
                }
            }
        }

        public string DieselDisplayClass
        {
            get
            {
                if (DieselLevel <= 15)
                {
                    return "fuel-danger";
                }
                else if (DieselLevel <= 50)
                {
                    return "fuel-warning";
                }
                else
                {
                    return "fuel-good";
                }
            }
        }


        public StoreOverview()
        {

        }

        public StoreOverview(DinocoStore store)
            : this()
        {
            if (store == null)
                return;

            this.StoreID = store.StoreID;
        }

        public void LoadFootTrafficResults(FootTrafficTelemetry dataAsObj)
        {
            if (dataAsObj == null)
                return;

            this.PeopleInStore = dataAsObj.Souls;
        }

        public void LoadFuelTankResults(FuelTankTelemetry dataAsObj)
        {
            if (dataAsObj == null)
                return;


            this.E85Level = dataAsObj.E85;
            this.AllinolLevel = dataAsObj.Allinol;
            this.DieselLevel = dataAsObj.Diesel;
        }

        public void LoadCoffeeMakerResults(CoffeeMakerTelemetry dataAsObj)
        {
            if (dataAsObj == null)
                return;

            this.CoffeeAge = dataAsObj.MinutesSinceLastBrew;
            this.CoffeeTemperature = dataAsObj.Temperature;
        }
    }
}

src/Dinoco.WebDashboard/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Dinoco.DataAccess.Interfaces;
using Dinoco.Shared.Helpers;
using Dinoco.Shared.Models.Telemetry;
using Dinoco.WebDashboard.Models;
using Dinoco.WebDashboard.Models.Home;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Dinoco.WebDashboard.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IStoreService _storeSrv;
        private readonly IDeviceService _deviceSrv;

        public HomeController(ILogger<HomeController> logger, IStoreService storeSrv, IDeviceService deviceSrv)
        {
            _logger = logger;
            _storeSrv = storeSrv;
            _deviceSrv = deviceSrv;
        }

        public async Task<IActionResult> Index()
        {
            HomeIndexModel model = new HomeIndexModel();

            var _stores = await _storeSrv.GetAllStores();

            foreach (var store in _stores)
            {
                StoreOverview so = new StoreOverview(store);

                var _deviceTypes = await _deviceSrv.GetDevicesForStore(so.StoreID);

                foreach (string s in _deviceTypes)
                {
                    List<object> d = await _deviceSrv.GetLastReadingsForDevice(so.StoreID, s, 1);

                    switch (s)
                    {
                        case "CoffeeMaker":
                            CoffeeMakerTelemetry cmData = DeviceDataHelper<CoffeeMakerTelemetry>.ParseSingle(d.FirstOrDefault());
                            so.LoadCoffeeMakerResults(cmData);
                            break;
                        case "FootTraffic":
                            FootTrafficTelemetry ftData = DeviceDataHelper<FootTrafficTelemetry>.ParseSingle(d.FirstOrDefault());
                            so.LoadFootTrafficResults(ftData);
                            break;
                        case "FuelTank":
                            FuelTankTelemetry FutData = DeviceDataHelper<FuelTankTelemetry>.ParseSingle(d.FirstOrDefault());
                            so.LoadFuelTankResults(FutData);
                            break;
                    }
                }

                model.Stores.Add(so);
            }

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Dinoco.WebDashboard/ViewComponents/AlertsViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Dinoco.DataAccess.Interfaces;
using Dinoco.Shared.Helpers;
using Dinoco.Shared.Models.Telemetry;
using Microsoft.AspNetCore.Mvc;

namespace Dinoco.WebDashboard.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        private readonly IStoreService _storeSrv;
        private readonly IDeviceService _sensorSrv;

        public AlertsViewComponent(IStoreService storeSrv, IDeviceService sensorSrv)
        {
            _storeSrv = storeSrv;
            _sensorSrv = sensorSrv;
        }

        public async Task<IViewComponentResult> InvokeAsync(int StoreID = 0)
        {
            int _take = (StoreID == 0) ? 5 : 100;

            List<object> sensorData = await _sensorSrv.GetLastReadingsForDevice(StoreID, "Alert", _take);
            List<GeneralMessageTelemetry> records = DeviceDataHelper<GeneralMessageTelemetry>.ParseMany(sensorData);
            return View(records);
        }


    }
}

src/Dinoco.WebDashboard/ViewComponents/EventsViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Dinoco.DataAccess.Interfaces;
using Dinoco.Shared.Helpers;
using Dinoco.Shared.Models.Telemetry;
using Microsoft.AspNetCore.Mvc;

namespace Dinoco.WebDashboard.ViewComponents
{
    public class EventsViewComponent : ViewComponent
    {
        private readonly IStoreService _storeSrv;
        private readonly IDeviceService _sensorSrv;

        public EventsViewComponent(IStoreService storeSrv, IDeviceService sensorSrv)
        {
            _storeSrv = storeSrv;
            _sensorSrv = sensorSrv;
        }

        public async Task<IViewComponentResult> InvokeAsync(int StoreID = 0)
        {
            int _take = (StoreID == 0) ? 5 : 100;

            List<object> sensorData = await _sensorSrv.GetLastReadingsForDevice(StoreID, "INFO", _take);
            List<GeneralMessageTelemetry> records = DeviceDataHelper<GeneralMessageTelemetry>.ParseMany(sensorData);
            return View(records);
        }
    }
}

src/Dinoco.WebDashboard/Views/Home/Index.cshtml
@model Dinoco.WebDashboard.Models.Home.HomeIndexModel

@{
    ViewData["Title"] = "Dashboard";
}

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header bg-DinocoBlue text-white">
                <h4><i class="fas fa-store-alt"></i> Store Overview:</h4>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th class="text-center" style="border-left: solid 1px #eee; border-right: solid 1px #eee;">Fuel Levels</th>
                            <th></th>
                        </tr>
                        <tr>
                            <th>Store</th>
                            <th>Coffee</th>
                            <th>
                                <div class="row">
                                    <div class="col text-center" style="border-left: solid 1px #eee; border-right: solid 1px #eee;">E85</div>
                                    <div class="col text-center" style="border-left: solid 1px #eee; border-right: solid 1px #eee;">Allinol</div>
                                    <div class="col text-center" style="border-left: solid 1px #eee; border-right: solid 1px #eee;">Diesel</div>
                                </div>
                            </th>
                            <th>Foot Traffic</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var store in Model.Stores)
                        {
                            <tr>
                                <td><a href="/Store/Index/@store.StoreID">Store #@store.StoreID</a></td>
                                <td>@store.CoffeeOverview (@store.CoffeeTemperature.ToString("N2") &deg;)</td>
                                <td>
                                    <div class="row">
                                        <div class="col text-center @store.E85DisplayClass" style="border-left: solid 1px #eee; border-right: solid 1px #eee;">@store.E85Level.ToString("N2") %</div>
                                        <div class="col text-center @store.AllinolDisplayClass" " style="border-left: solid 1px #eee; border-right: solid 1px #eee;">@store.AllinolLevel.ToString("N2") %</div>
                                        <div class="col text-center @store.DieselDisplayClass" " style="border-left: solid 1px #eee; border-right: solid 1px #eee;">@store.DieselLevel.ToString("N2") %</div>
                                    </div>
                                </td>
                                <td>@store.FootTrafficOverview</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col">
        @await Component.InvokeAsync("Alerts", new { }) 
    </div>
    <div class="col">
        @await Component.InvokeAsync("Events", new { })
    </div>
</div>
